"""
name_mapper.py — Resolve free-text company names to NSE/BSE ticker symbols.

Priority chain:
  1. Custom mappings stored in DB (portfolio_symbol_mappings table)
  2. Hardcoded RAW_MAP (300+ entries)
  3. Auto-generated reverse lookup from assets already in DB
  4. Partial prefix match
  5. None — caller adds to unmapped list
"""
from __future__ import annotations
import re
from typing import Optional


def normalize(s: str) -> str:
    s = s.lower()
    s = re.sub(r"[^a-z0-9 ]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def looks_like_ticker(s: str) -> bool:
    stripped = s.strip()
    if len(stripped) > 12:
        return False
    if stripped.lower() != stripped.upper() and stripped != stripped.upper():
        return False
    if stripped.count(" ") > 1:
        return False
    return True


RAW_MAP: dict[str, str] = {
    # ── Banks ────────────────────────────────────────────────────────
    "hdfc bank": "HDFCBANK",
    "hdfc bank limited": "HDFCBANK",
    "kotak mahindra bank": "KOTAKBANK",
    "kotak mahindra bank limited": "KOTAKBANK",
    "kotak bank": "KOTAKBANK",
    "icici bank": "ICICIBANK",
    "icici bank limited": "ICICIBANK",
    "axis bank": "AXISBANK",
    "axis bank limited": "AXISBANK",
    "federal bank": "FEDERALBNK",
    "the federal bank limited": "FEDERALBNK",
    "federal bank limited": "FEDERALBNK",
    "idfc first bank": "IDFCFIRSTB",
    "idfc first bank limited": "IDFCFIRSTB",
    "south indian bank": "SOUTHBANK",
    "the south indian bank limited": "SOUTHBANK",
    "south indian bank limited": "SOUTHBANK",
    "dcb bank": "DCBBANK",
    "dcb bank limited": "DCBBANK",
    "rbl bank": "RBLBANK",
    "rbl bank limited": "RBLBANK",
    "equitas small finance bank": "EQUITASBNK",
    "equitas small finance bank limited": "EQUITASBNK",
    "equitas sfb": "EQUITASBNK",
    "karnataka bank": "KTKBANK",
    "the karnataka bank limited": "KTKBANK",
    "jammu and kashmir bank": "J&KBANK",
    "j k bank": "J&KBANK",
    "bank of india": "BANKINDIA",
    "bank of india limited": "BANKINDIA",
    "equitas": "EQUITAS",
    "state bank of india": "SBIN",
    "sbi": "SBIN",
    "punjab national bank": "PNB",
    "pnb": "PNB",
    "bank of baroda": "BANKBARODA",
    "canara bank": "CANBK",
    "union bank of india": "UNIONBANK",
    "indusind bank": "INDUSINDBK",
    "yes bank": "YESBANK",
    "bandhan bank": "BANDHANBNK",

    # ── HDFC Group ───────────────────────────────────────────────────
    "hdfc limited": "HDFC",
    "hdfc ltd": "HDFC",
    "hdfc": "HDFC",
    "hdfc asset management company": "HDFCAMC",
    "hdfc amc": "HDFCAMC",
    "hdfc asset management": "HDFCAMC",
    "hdfc asset management company limited": "HDFCAMC",
    "hdfc life insurance": "HDFCLIFE",
    "hdfc life": "HDFCLIFE",
    "hdfc life insurance company limited": "HDFCLIFE",

    # ── Bajaj Group ──────────────────────────────────────────────────
    "bajaj finance": "BAJFINANCE",
    "bajaj finance limited": "BAJFINANCE",
    "bajaj finserv": "BAJAJFINSV",
    "bajaj finserv limited": "BAJAJFINSV",
    "bajaj finserv ltd": "BAJAJFINSV",
    "bajaj auto": "BAJAJ-AUTO",
    "bajaj auto limited": "BAJAJ-AUTO",
    "bajaj consumer care": "BAJAJCON",
    "bajaj consumer care limited": "BAJAJCON",
    "bajaj consumer": "BAJAJCON",

    # ── Pharma ──────────────────────────────────────────────────────
    "divi s laboratories": "DIVISLAB",
    "divi laboratories": "DIVISLAB",
    "divis laboratories": "DIVISLAB",
    "divi s laboratories limited": "DIVISLAB",
    "piramal pharma": "PPLPHARMA",
    "piramal pharma limited": "PPLPHARMA",
    "piramal pharma ltd": "PPLPHARMA",
    "lupin": "LUPIN",
    "lupin limited": "LUPIN",
    "sun pharmaceutical": "SUNPHARMA",
    "sun pharmaceutical industries limited": "SUNPHARMA",
    "sun pharma": "SUNPHARMA",
    "zydus lifesciences": "ZYDUSLIFE",
    "zydus lifesciences limited": "ZYDUSLIFE",
    "zydus cadila": "ZYDUSLIFE",
    "ajanta pharma": "AJANTPHARM",
    "ajanta pharma limited": "AJANTPHARM",
    "sanofi india": "SANOFI",
    "sanofi india limited": "SANOFI",
    "abbott india": "ABBOTINDIA",
    "abbott india limited": "ABBOTINDIA",
    "glaxosmithkline pharmaceuticals": "GLAXO",
    "glaxosmithkline pharmaceuticals limited": "GLAXO",
    "gsk pharmaceuticals": "GLAXO",
    "eris lifesciences": "ERIS",
    "eris lifesciences limited": "ERIS",
    "procter gamble health": "PGHL",
    "procter and gamble health": "PGHL",
    "procter gamble health limited": "PGHL",
    "p g health": "PGHL",
    "morepen laboratories": "MOREPENLAB",
    "morepen laboratories limited": "MOREPENLAB",
    "blue jet healthcare": "BLUEJET",
    "blue jet healthcare limited": "BLUEJET",
    "cipla": "CIPLA",
    "cipla limited": "CIPLA",
    "dr reddy": "DRREDDY",
    "dr reddys laboratories": "DRREDDY",
    "dr reddys laboratories limited": "DRREDDY",
    "torrent pharmaceuticals": "TORNTPHARM",
    "torrent pharma": "TORNTPHARM",
    "ipca laboratories": "IPCALAB",
    "alkem laboratories": "ALKEM",

    # ── Insurance ────────────────────────────────────────────────────
    "star health and allied insurance": "STARHEALTH",
    "star health and allied insurance company": "STARHEALTH",
    "star health allied insurance": "STARHEALTH",
    "star health": "STARHEALTH",
    "icici lombard": "ICICIGI",
    "icici lombard general insurance": "ICICIGI",
    "icici lombard general insurance company limited": "ICICIGI",
    "sbi life insurance": "SBILIFE",
    "max financial services": "MFSL",
    "lic of india": "LICI",

    # ── NBFC / Finance ───────────────────────────────────────────────
    "manappuram finance": "MANAPPURAM",
    "manappuram finance limited": "MANAPPURAM",
    "lic housing finance": "LICHSGFIN",
    "lic housing finance limited": "LICHSGFIN",
    "gic housing finance": "GICHSGFIN",
    "gic housing finance limited": "GICHSGFIN",
    "mas financial services": "MASFIN",
    "mas financial services limited": "MASFIN",
    "arman financial services": "ARMANFIN",
    "arman financial services limited": "ARMANFIN",
    "aptus value housing finance": "APTUS",
    "aptus value housing finance india limited": "APTUS",
    "muthoot capital services": "MUTHOOTCAP",
    "muthoot capital services limited": "MUTHOOTCAP",
    "srg housing finance": "SRGHFL",
    "power finance corporation": "PFC",
    "power finance corporation limited": "PFC",
    "five star business finance": "FIVESTAR",
    "five star business finance limited": "FIVESTAR",
    "fivestar business finance": "FIVESTAR",
    "care ratings": "CARERATING",
    "care ratings limited": "CARERATING",
    "crisil": "CRISIL",
    "crisil limited": "CRISIL",
    "icra": "ICRA",
    "icra limited": "ICRA",
    "dhfl": "DHFL",
    "dewan housing finance": "DHFL",
    "idfc": "IDFC",
    "idfc limited": "IDFC",
    "repco home finance": "REPCO",
    "repco": "REPCO",
    "muthoot finance": "MUTHOOTFIN",
    "shriram finance": "SHRIRAMFIN",
    "bajaj housing finance": "BAJAJHFL",
    "pnb housing finance": "PNBHOUSING",
    "can fin homes": "CANFINHOME",
    "m&m financial services": "M&MFIN",
    "mahindra finance": "M&MFIN",
    "cholamandalam investment": "CHOLAFIN",
    "chola finance": "CHOLAFIN",

    # ── IT / Tech ────────────────────────────────────────────────────
    "infosys": "INFY",
    "infosys limited": "INFY",
    "tata consultancy services": "TCS",
    "tata consultancy services limited": "TCS",
    "hcl technologies": "HCLTECH",
    "hcl technologies limited": "HCLTECH",
    "tech mahindra": "TECHM",
    "tech mahindra limited": "TECHM",
    "paytm": "PAYTM",
    "one97 communications": "PAYTM",
    "one97 communications limited": "PAYTM",
    "intellect design arena": "INTELLECT",
    "intellect design arena limited": "INTELLECT",
    "kellton tech": "KELLTONTEC",
    "kellton tech solutions": "KELLTONTEC",
    "indian energy exchange": "IEX",
    "indian energy exchange limited": "IEX",
    "wipro": "WIPRO",
    "wipro limited": "WIPRO",
    "ltimindtree": "LTIM",
    "l t mindtree": "LTIM",
    "mphasis": "MPHASIS",
    "persistent systems": "PERSISTENT",
    "coforge": "COFORGE",
    "zensar technologies": "ZENSARTECH",
    "kpit technologies": "KPITTECH",

    # ── Consumer / FMCG ──────────────────────────────────────────────
    "asian paints": "ASIANPAINT",
    "asian paints limited": "ASIANPAINT",
    "marico": "MARICO",
    "marico limited": "MARICO",
    "itc": "ITC",
    "itc limited": "ITC",
    "jyothy labs": "JYOTHYLAB",
    "jyothy labs limited": "JYOTHYLAB",
    "jyothy laboratories": "JYOTHYLAB",
    "pidilite industries": "PIDILITIND",
    "pidilite industries limited": "PIDILITIND",
    "gillete india": "GILLETTE",
    "gillette india": "GILLETTE",
    "gillette india limited": "GILLETTE",
    "havells india": "HAVELLS",
    "havells india limited": "HAVELLS",
    "vstt industries": "VSTIND",
    "vst industries": "VSTIND",
    "vst industries limited": "VSTIND",
    "titan": "TITAN",
    "titan company": "TITAN",
    "titan company limited": "TITAN",
    "united breweries": "UBL",
    "united breweries limited": "UBL",
    "whirlpool of india": "WHIRLPOOL",
    "whirlpool of india limited": "WHIRLPOOL",
    "whirlpool india": "WHIRLPOOL",
    "honasa consumer": "HONASA",
    "honasa consumer limited": "HONASA",
    "indigo paints": "INDIGOPNTS",
    "indigo paints limited": "INDIGOPNTS",
    "pc jeweller": "PCJEWELLER",
    "pc jeweller limited": "PCJEWELLER",
    "hindustan unilever": "HINDUNILVR",
    "hul": "HINDUNILVR",
    "hindustan unilever limited": "HINDUNILVR",
    "nestle india": "NESTLEIND",
    "britannia industries": "BRITANNIA",
    "dabur india": "DABUR",
    "godrej consumer products": "GODREJCP",
    "emami": "EMAMILTD",
    "colgate palmolive india": "COLPAL",
    "radico khaitan": "RADICO",
    "united spirits": "MCDOWELL-N",
    "tata consumer products": "TATACONSUM",
    "varun beverages": "VBL",
    "avenue supermarts": "DMART",
    "dmart": "DMART",
    "trent": "TRENT",
    "kalyan jewellers": "KALYANKJIL",
    "senco gold": "SENCO",

    # ── Auto ─────────────────────────────────────────────────────────
    "maruti suzuki": "MARUTI",
    "maruti suzuki india limited": "MARUTI",
    "maruti": "MARUTI",
    "eicher motors": "EICHERMOT",
    "eicher motors limited": "EICHERMOT",
    "samvardhana motherson": "MOTHERSON",
    "samvardhana motherson international": "MOTHERSON",
    "motherson sumi": "MOTHERSON",
    "tata motors": "TATAMOTORS",
    "tata motors limited": "TATAMOTORS",
    "mahindra and mahindra": "M&M",
    "mahindra mahindra": "M&M",
    "hero motocorp": "HEROMOTOCO",
    "bajaj auto ltd": "BAJAJ-AUTO",
    "tvs motor": "TVSMOTOR",
    "tvs motor company": "TVSMOTOR",
    "ashok leyland": "ASHOKLEY",
    "escorts kubota": "ESCORTS",
    "mrf": "MRF",
    "apollo tyres": "APOLLOTYRE",
    "ceat": "CEATLTD",

    # ── Infra / Engineering ───────────────────────────────────────────
    "larsen toubro": "LT",
    "larsen and toubro": "LT",
    "l t": "LT",
    "lt": "LT",
    "larsen toubro limited": "LT",
    "bhel": "BHEL",
    "bharat heavy electricals": "BHEL",
    "bharat heavy electricals limited": "BHEL",
    "cg power": "CGPOWER",
    "cg power and industrial solutions": "CGPOWER",
    "cg power and industrial solutions limited": "CGPOWER",
    "adani ports": "ADANIPORTS",
    "adani ports and special economic zone": "ADANIPORTS",
    "adani ports and special economic zone limited": "ADANIPORTS",
    "genus power": "GENUSPOWER",
    "genus power infrastructures": "GENUSPOWER",
    "genus power infrastructures limited": "GENUSPOWER",
    "genus paper": "GENUSPAPER",
    "genus paper boards limited": "GENUSPAPER",
    "triveni engineering": "TRIVENI",
    "triveni engineering and industries": "TRIVENI",
    "triveni engineering industries limited": "TRIVENI",
    "pi industries": "PIIND",
    "pi industries limited": "PIIND",
    "kaveri seed": "KSCL",
    "kaveri seed company": "KSCL",
    "kaveri seed company limited": "KSCL",
    "astec lifesciences": "ASTEC",
    "astec lifesciences limited": "ASTEC",
    "siemens": "SIEMENS",
    "abb india": "ABB",
    "thermax": "THERMAX",
    "bharat electronics": "BEL",
    "bharat electronics limited": "BEL",
    "hindustan aeronautics": "HAL",
    "hal": "HAL",
    "cochin shipyard": "COCHINSHIP",
    "mazagon dock shipbuilders": "MAZDOCK",
    "kalpataru projects": "KPIL",
    "knr constructions": "KNRCON",
    "irb infrastructure": "IRB",

    # ── Commodities / Energy ──────────────────────────────────────────
    "coal india": "COALINDIA",
    "coal india limited": "COALINDIA",
    "ongc": "ONGC",
    "oil and natural gas corporation": "ONGC",
    "oil and natural gas corporation limited": "ONGC",
    "vedanta": "VEDL",
    "vedanta limited": "VEDL",
    "tata steel": "TATASTEEL",
    "tata steel limited": "TATASTEEL",
    "reliance industries": "RELIANCE",
    "reliance industries limited": "RELIANCE",
    "reliance": "RELIANCE",
    "multi commodity exchange": "MCX",
    "multi commodity exchange of india": "MCX",
    "multi commodity exchange of india limited": "MCX",
    "mcx": "MCX",
    "jsw steel": "JSWSTEEL",
    "hindalco industries": "HINDALCO",
    "nmdc": "NMDC",
    "sail": "SAIL",
    "steel authority of india": "SAIL",
    "ntpc": "NTPC",
    "power grid corporation": "POWERGRID",
    "adani green energy": "ADANIGR",
    "adani enterprises": "ADANIENT",
    "adani total gas": "ATGL",
    "gujarat gas": "GUJARATGAS",
    "indraprastha gas": "IGL",
    "mahanagar gas": "MGL",
    "bpcl": "BPCL",
    "bharat petroleum": "BPCL",
    "hpcl": "HINDPETRO",
    "hindustan petroleum": "HINDPETRO",
    "ioc": "IOC",
    "indian oil corporation": "IOC",
    "gail": "GAIL",
    "gail india limited": "GAIL",
    "oil india": "OIL",
    "petronet lng": "PETRONET",

    # ── Specialty / Others ────────────────────────────────────────────
    "akzo india": "AKZOINDIA",
    "akzo nobel india": "AKZOINDIA",
    "jsk dulux": "AKZOINDIA",
    "jsw dulux": "AKZOINDIA",
    "glenmark pharmaceuticals": "GLENMARK",
    "glenmark pharmaceuticals limited": "GLENMARK",
    "glenmark": "GLENMARK",
    "apollo pipes": "APOLLOPIPE",
    "apollo pipes limited": "APOLLOPIPE",
    "alok industries": "ALOKINDS",
    "alok industries limited": "ALOKINDS",
    "hdil": "HDIL",
    "housing development and infrastructure": "HDIL",
    "ibrealest": "IBREALEST",
    "equinox india developments": "IBREALEST",
    "swiggy": "SWIGGY",
    "bse": "BSE",
    "bse limited": "BSE",
    "sheela foam": "SFL",
    "sheela foam limited": "SFL",
    "tips music": "TIPSMUSIC",
    "tips music limited": "TIPSMUSIC",
    "nam india": "NAM-INDIA",
    "nippon life india asset management": "NAM-INDIA",
    "nippon life india asset management limited": "NAM-INDIA",
    "leel electricals": "LEEL",
    "leel electricals limited": "LEEL",
    "cmi limited": "CMICABLES",
    "cmi cables": "CMICABLES",
    "nippon india etf gold bees": "GOLDBEES",
    "gold bees": "GOLDBEES",
    "nippon india etf nifty 50 bees": "NIFTYBEES",
    "nifty bees": "NIFTYBEES",
    "niftybees": "NIFTYBEES",
    "sanofi consumer healthcare": "SANOFICONR",
    "pc jewellers": "PCJEWELLER",
    "zomato": "ZOMATO",
    "nykaa": "FSN",
    "fsn e commerce ventures": "FSN",
    "policy bazaar": "POLICYBZR",
    "pb fintech": "POLICYBZR",
    "delhivery": "DELHIVERY",
    "cartrade tech": "CARTRADE",
    "mapmyindia": "MAPMYINDIA",
    "ce info systems": "MAPMYINDIA",
    "irctc": "IRCTC",
    "indian railway catering": "IRCTC",
    "rites": "RITES",
    "container corporation": "CONCOR",
    "concor": "CONCOR",
    "interglobe aviation": "INDIGO",
    "indigo": "INDIGO",
    "spicejet": "SPICEJET",
    "oberoi realty": "OBEROIRLTY",
    "dlf": "DLF",
    "godrej properties": "GODREJPROP",
    "prestige estates": "PRESTIGE",
    "brigade enterprises": "BRIGADE",
    "phoenix mills": "PHOENIXLTD",
    "nse india": "NSEIND",
    "crompton greaves consumer": "CROMPTON",
    "orient electric": "ORIENTELEC",
    "voltas": "VOLTAS",
    "blue star": "BLUESTAR",
    "dixon technologies": "DIXON",
    "amber enterprises": "AMBER",
    "pg electroplast": "PGEL",
    "kaynes technology": "KAYNES",
    "syrma sgs technology": "SYRMA",
    "tata elxsi": "TATAELXSI",
    "minda industries": "MINDAIND",
    "sona blw precision": "SONACOMS",
    "valeo lighting systems": "VALEO",
}


def build_dynamic_map(db_assets: list[dict]) -> dict[str, str]:
    dyn: dict[str, str] = {}
    for a in db_assets:
        sym  = a["symbol"]
        name = a.get("name", "")
        if name and name != sym:
            key = normalize(name)
            if key:
                dyn[key] = sym
    return dyn


def resolve_symbol(
    raw_name: str,
    custom_map: dict[str, str] | None = None,
    dynamic_map: dict[str, str] | None = None,
) -> Optional[str]:
    raw_name = raw_name.strip()

    if looks_like_ticker(raw_name):
        return raw_name.upper().replace(" ", "")

    key = normalize(raw_name)
    if not key:
        return None

    if custom_map and key in custom_map:
        return custom_map[key]

    if key in RAW_MAP:
        return RAW_MAP[key]

    if dynamic_map and key in dynamic_map:
        return dynamic_map[key]

    for map_dict in [custom_map or {}, RAW_MAP, dynamic_map or {}]:
        for k, v in map_dict.items():
            if key.startswith(k) or k.startswith(key):
                return v

    return None
